export const NotificationType = {
  REGISTRATION_APPROVED: "REGISTRATION_APPROVED",
  REGISTRATION_REJECTED: "REGISTRATION_REJECTED",
  CHECKIN_SUCCESS: "CHECKIN_SUCCESS",

  HOST_ASSIGNED: "HOST_ASSIGNED",
  EVENT_UPDATED: "EVENT_UPDATED",
  EVENT_REMINDER: "EVENT_REMINDER",

  NEW_EVENT: "NEW_EVENT",
  FAVORITE_REMINDER: "FAVORITE_REMINDER"
} as const;